name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    
    - name: Force xcode 13.4.1
      run: sudo xcode-select -switch /Applications/Xcode_13.4.1.app
    
    - name: Build
      run: xcodebuild build-for-testing -scheme TileFeed -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11'
    
    - name: Run tests
      run: xcodebuild test-without-building -scheme TileFeed -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11'
