name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: xcodebuild build-for-testing -scheme TileFeed -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11'
    - name: Run tests
      run: xcodebuild test-without-building -scheme TileFeed -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11'
